# Generated by Django 3.0.7 on 2020-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('Total_cases', models.IntegerField()),
                ('Today_cases', models.IntegerField()),
                ('Total_deaths', models.IntegerField()),
                ('Today_deaths', models.IntegerField()),
                ('Total_recovered', models.IntegerField()),
                ('Active_cases', models.IntegerField()),
                ('Critical_cases', models.IntegerField()),
                ('Cases_per_one_million', models.IntegerField()),
                ('Deaths_per_one_million', models.IntegerField()),
                ('Total_tests', models.IntegerField()),
                ('Tests_per_one_million', models.IntegerField()),
            ],
        ),
    ]
