# Generated by Django 3.0.7 on 2020-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarddata',
            options={'verbose_name_plural': 'Dashboard'},
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='Active_cases',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='Total_recovered',
            field=models.IntegerField(blank=True),
        ),
    ]
