# Generated by Django 3.0.7 on 2020-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200604_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='Active_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='Total_recovered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
