# Generated by Django 3.0.7 on 2020-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200604_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='Last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
