# Generated by Django 3.0.7 on 2020-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboarddata_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('Slug', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'CountrySlug',
            },
        ),
    ]
