# Generated by Django 3.0.7 on 2020-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_countryslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='summaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('Country_code', models.CharField(blank=True, max_length=10)),
                ('Slug', models.CharField(blank=True, max_length=20)),
                ('Total_cases', models.IntegerField()),
                ('New_cases', models.IntegerField()),
                ('Total_deaths', models.IntegerField()),
                ('New_deaths', models.IntegerField()),
                ('Total_recovered', models.IntegerField(blank=True, null=True)),
                ('New_recovered', models.IntegerField(blank=True, null=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Summary Data',
            },
        ),
        migrations.AlterModelOptions(
            name='countryslug',
            options={'verbose_name_plural': 'Country to Slug'},
        ),
    ]
