# Generated by Django 3.0.7 on 2020-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200607_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydata',
            name='Last_updated',
            field=models.DateTimeField(),
        ),
    ]
