# Generated by Django 2.2.7 on 2020-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_historicaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
