# Generated by Django 2.2.7 on 2020-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
                ('Confirmed', models.TextField()),
                ('Date', models.TextField()),
                ('Deaths', models.TextField()),
                ('Recovered', models.TextField()),
                ('Active', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Historical Data',
            },
        ),
    ]
