# Generated by Django 2.2.7 on 2020-06-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_historicaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
