# Generated by Django 2.2.7 on 2020-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_historicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarydata',
            name='Population',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='Size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
